# version: "3"docker buildx create \ --name container-builder \ --driver docker-container \--bootstrap --use
services:
  strapi:
    # container_name: Xefro_View_Api_V5
    build: .
    # Change This Image name to Custom Image Docker Hub name Example sonata93/demo-app
    image: mosonata/xefro-view-api-v5-img1:latest
    restart: unless-stopped
    env_file: ./.env.production
   # We comment this line because we passing the env from envFile paramter
    # environment:
    #   DATABASE_CLIENT: ${DATABASE_CLIENT}
    #   DATABASE_HOST: strapiDB
    #   DATABASE_PORT: ${DATABASE_PORT}
    #   DATABASE_NAME: ${DATABASE_NAME}
    #   DATABASE_USERNAME: ${DATABASE_USERNAME}
    #   DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    #   JWT_SECRET: ${JWT_SECRET}
    #   ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    #   APP_KEYS: ${APP_KEYS}
    #   NODE_ENV: ${NODE_ENV}
    deploy:
      replicas: 3
      # placement:
      #   max_replicas_per_node: 1
      update_config:
        parallelism: 3
        delay: 50s
      restart_policy:
        condition: on-failure
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      # - ./.env:/opt/app/.env  // We comment this line because we passing the env from envFile paramter
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1339:1339"
    # networks:
    #   - strapi
    depends_on:
      - strapiDB

  strapiDB:
    # container_name: strapiDB
    #platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./.env.production
    image: postgres:12.0-alpine
   # We comment this line because we passing the env from envFile paramter
    # environment:
    #   POSTGRES_USER: ${DATABASE_USERNAME}
    #   POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    #   POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5439:5432"
      # also we comment this because we using docker Swarm 
    # networks:
    #   - strapi

volumes:
  strapi-data:

# networks:
#   strapi:
#     name: Strapi
#     driver: bridge